channels:
- conda-forge
dependencies:
- python=3.11.5
- pip=23.2.1
- pip:
  - openai
  - chromadb
  - python-dotenv
  - azureml-inference-server-http
  - pandas
  - numpy
  - scikit-learn
  - scipy
name: oai-env